function [] = eyenb( DATA,samples )
DATA=DATA-min(DATA);
DATA=DATA/max(DATA)*5;

n_l=1:length(DATA);  
m_l=samples;   
s_l=1/m_l;         
xi_l=1:s_l:length(DATA);
DATA= interp1(n_l,DATA,xi_l,'linear');

H = commscope.eyediagram('SamplesPerSymbol', samples, ...
                         'SymbolsPerTrace', 2, ...
                         'MinimumAmplitude', 0, ...
                         'MaximumAmplitude', 5, ...
                         'AmplitudeResolution', 0.010, ...
                         'MeasurementDelay', 0, ...
                         'PlotType', '2D Color', ...
                         'PlotTimeOffset', 0, ...
                         'PlotPDFRange', [0 1], ...
                         'ColorScale', 'log', ...
                         'RefreshPlot', 'on');

update(H,DATA);
H.PlotTimeOffset = 0;
plot(H, jet(64));

end

